/**
 * Netlify 构建脚本
 * 在 Netlify 构建时自动运行：
 * 1. 读取 server.js（本地开发版本，有 app.listen）
 * 2. 去掉 app.listen 及以后的代码
 * 3. 加上 serverless-http 包装，转为 Netlify Function
 * 4. 输出到 netlify/functions/api.js
 */
const fs = require('fs');
const path = require('path');

console.log('>>> Running build.js: converting server.js to Netlify Function');

// 1. 读取 server.js
const serverPath = path.join(__dirname, 'server.js');
let code = fs.readFileSync(serverPath, 'utf8');
console.log(' - Read server.js:', code.length, 'chars');

// 2. 去掉 app.listen(...) 直到文件末尾
//    匹配：app.listen( ... ); 及之后的所有内容
const listenMatch = code.match(/app\.listen\s*\(/);
if (listenMatch) {
  const cutIndex = listenMatch.index;
  code = code.slice(0, cutIndex);
  console.log(' - Removed app.listen block, code now:', code.length, 'chars');
} else {
  console.log(' - Warning: app.listen not found, using full code');
}

// 3. 加上 serverless-http 导出
code += `\n\n// ===== Auto-generated by build.js for Netlify Functions =====\nconst serverless = require('serverless-http');\nconst _handler = serverless(app);\nexports.handler = async (event, context) => {\n  // 防止 Netlify 回调挂起：等待所有 DB 连接释放（可选）\n  const result = await _handler(event, context);\n  return result;\n};\n`;

// 4. 确保输出目录存在并写入文件
const outDir = path.join(__dirname, 'netlify', 'functions');
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, 'api.js');
fs.writeFileSync(outPath, code, 'utf8');
console.log(' - Wrote', outPath, '(' + code.length + ' chars)');

console.log('>>> build.js completed successfully');
